.pragma library

const extensions = {
    'aac': 'Аудиофайл',
    'adt': 'Аудиофайл',
    'adts': 'Аудиофайл',
    'accdb': 'Файл базы данных Microsoft Access',
    'accde': 'Файл Microsoft Access только для выполнения',
    'accdr': 'База данных Microsoft Access',
    'accdt': 'Шаблон базы данных Microsoft Access',
    'aif': 'Аудиофайл',
    'aifc': 'Аудиофайл',
    'aiff': 'Аудиофайл',
    'aspx': 'Файл Active Server Page ASP.NET',
    'avi': 'Файл аудио или видео AVI',

    'bat': 'Пакетный файл PC',
    'bin': 'Двоичный сжатый файл',
    'bmp': 'Файл точечного рисунка',

    'cab': 'CAB-файл Windows',
    'cda': 'Дорожка компакт-диска',
    'csv': 'Файл данных с разделителями-запятыми',

    'dif': 'Файл таблицы формата DIF',
    'dll': 'Динамическая библиотека',
    'doc': 'Документ Microsoft Word до Word 2007',
    'docm': 'Документ Microsoft Word с включенной поддержкой макросов',
    'docx': 'Документ Microsoft Word',
    'dot': 'Шаблон Microsoft Word до Word 2007',
    'dotx': 'Шаблон Microsoft Word',

    'eml': 'Файл электронной почты',
    'eps': 'Файл Encapsulated PostScript',
    'exe': 'Исполняемый файл',

    'flv': 'Видеофайл совместимый с Flash',

    'gif': 'Изображение GIF',

    'htm': 'Страница на языке разметки HTML',
    'html': 'Страница на языке разметки HTML',

    'ini': 'Файл конфигурации для инициализации Windows',
    'iso': 'Образ диска ISO-9660',

    'jar': 'Файл архитектуры Java',
    'jpg': 'Изображение JPEG',
    'jpeg': 'Изображение JPEG',

    'm4a': 'Звуковой файл MPEG-4',
    'mdb': 'База данных Microsoft Access до Access 2007',
    'mid': 'Файл интерфейса Musical Instrument Digital Interface',
    'midi': 'Файл интерфейса Musical Instrument Digital Interface',

    'mov': 'Видеофайл',
    'mp3': 'Аудиофайл',
    'mp4': 'Видеофайл',
    'mpeg': 'Видеофайл',
    'mpg': 'Поток в формате MPEG 1',
    'msi': 'Файл установщика Microsoft',
    'mui': 'Файл многоязычного пользовательского интерфейса',

    'pdf': 'Файл Portable Document Format',
    'png': 'Файл Portable Network Graphics',
    'pot': 'Шаблон Microsoft PowerPoint',
    'potm': 'Шаблон Microsoft PowerPoint с включенной поддержкой макросов',
    'potx': 'Шаблон Microsoft PowerPoint',
    'ppam': 'Надстройка Microsoft PowerPoint',
    'pps': 'Слайд-шоу Microsoft PowerPoint до PowerPoint 2007',
    'ppsm': 'Слайд-шоу Microsoft PowerPoint с включенной поддержкой макросов',
    'ppsx': 'Слайд-шоу Microsoft PowerPoint',
    'ppt': 'Формат Microsoft PowerPoint до PowerPoint 2007',
    'pptm': 'Презентация Microsoft PowerPoint с включенной поддержкой макросов',
    'pptx': 'Презентация Microsoft PowerPoint',
    'psd': 'Файл Adobe Photoshop',
    'pst': 'Хранилище данных Outlook',
    'pub': 'Файл Microsoft Publisher',

    'rar': 'Архив',
    'rtf': 'Текстовый файл RTF',

    'sldm': 'Слайд Microsoft PowerPoint с включенной поддержкой макросов',
    'sldx': 'Слайд Microsoft PowerPoint',
    'swf': 'Файл Shockwave Flash',
    'sys': 'Файл системных параметров',

    'tif': 'Файл Tagged Image Format',
    'tiff': 'Файл Tagged Image Format',
    'tmp': 'Файл временных данных',
    'txt': 'Текстовый файл',

    'vob': 'Файл видеообъекта',
    'vsd': 'Рисунок Microsoft Visio до Visio 2013',
    'vsdm': 'Рисунок Microsoft Visio с включенными макросами',
    'vsdx': 'Файл рисунка Microsoft Visio',
    'vss': 'Трафарет Microsoft Visio до Visio 2013',
    'vssm': 'Трафарет Microsoft Visio с включенными макросами',
    'vst': 'Шаблон Microsoft Visio до Visio 2013',
    'vstm': 'Шаблон Microsoft Visio с включенными макросами',
    'vstx': 'Шаблон Microsoft Visio',

    'wav': 'Аудиофайл',
    'wbk': 'Архивный документ Microsoft Word',
    'wks': 'Файл Microsoft Works',
    'wma': 'Файл Windows Media Audio',
    'wmd': 'Файл Windows Media Download',
    'wmv': 'Файл Windows Media Video',
    'wmz': 'Файл обложек Windows Media',
    'wms': 'Файл обложек Windows Media',
    'wpd': 'Документ WordPerfect',
    'wp5': 'Документ WordPerfect',
    'xla': 'Файл надстройки или макроса Microsoft Excel',
    'xlam': 'Надстройка Microsoft Excel после Excel 2007',
    'xll': 'Надстройка Microsoft Excel на основе DLL',
    'xlm': 'Макрос Microsoft Excel до Excel 2007',
    'xls': 'Рабочая книга Microsoft Excel до Excel 2007',
    'xlsm': 'Рабочая книга Microsoft Excel с включенной поддержкой макросов после Excel 2007',
    'xlsx': 'Рабочая книга Microsoft Excel после Excel 2007',
    'xlt': 'Шаблон Microsoft Excel до Excel 2007',
    'xltm': 'Шаблон Microsoft Excel с включенной поддержкой макросов',
    'xltx': 'Шаблон Microsoft Excel после Excel 2007',
    'xps': 'Документ на основе XML',

    'zip': 'Архив'
}

const iconPaths = {
    'aac': 'qrc:/qtx/icons/file-types/audio.svg',
    'adt': 'qrc:/qtx/icons/file-types/audio.svg',
    'adts': 'qrc:/qtx/icons/file-types/audio.svg',
    'accdb': 'qrc:/qtx/icons/file-types/object.svg',
    'accde': 'qrc:/qtx/icons/file-types/object.svg',
    'accdr': 'qrc:/qtx/icons/file-types/object.svg',
    'accdt': 'qrc:/qtx/icons/file-types/object.svg',
    'aif': 'qrc:/qtx/icons/file-types/audio.svg',
    'aifc': 'qrc:/qtx/icons/file-types/audio.svg',
    'aiff': 'qrc:/qtx/icons/file-types/audio.svg',
    'aspx': 'qrc:/qtx/icons/file-types/code.svg',
    'avi': 'qrc:/qtx/icons/file-types/video.svg',
    'bat': 'qrc:/qtx/icons/file-types/terminal.svg',
    'bin': 'qrc:/qtx/icons/file-types/archive.svg',
    'bmp': 'qrc:/qtx/icons/file-types/image.svg',
    'cda': 'qrc:/qtx/icons/file-types/audio.svg',
    'csv': 'qrc:/qtx/icons/file-types/code.svg',
    'dif': 'qrc:/qtx/icons/file-types/bill.svg',
    'dll': 'qrc:/qtx/icons/file-types/settings.svg',
    'doc': 'qrc:/qtx/icons/file-types/text.svg',
    'docm': 'qrc:/qtx/icons/file-types/bill.svg',
    'docx': 'qrc:/qtx/icons/file-types/text.svg',
    'dot': 'qrc:/qtx/icons/file-types/text.svg',
    'dotx': 'qrc:/qtx/icons/file-types/text.svg',
    'eps': 'qrc:/qtx/icons/file-types/code.svg',
    'exe': 'qrc:/qtx/icons/file-types/terminal.svg',
    'flv': 'qrc:/qtx/icons/file-types/video.svg',
    'gif': 'qrc:/qtx/icons/file-types/image.svg',
    'htm': 'qrc:/qtx/icons/file-types/html.svg',
    'html': 'qrc:/qtx/icons/file-types/html.svg',
    'ini': 'qrc:/qtx/icons/file-types/settings.svg',
    'iso': 'qrc:/qtx/icons/file-types/archive.svg',
    'jar': 'qrc:/qtx/icons/file-types/code.svg',
    'jpg': 'qrc:/qtx/icons/file-types/image.svg',
    'jpeg': 'qrc:/qtx/icons/file-types/image.svg',
    'm4a': 'qrc:/qtx/icons/file-types/audio.svg',
    'mdb': 'qrc:/qtx/icons/file-types/object.svg',
    'mid': 'qrc:/qtx/icons/file-types/audio.svg',
    'midi': 'qrc:/qtx/icons/file-types/audio.svg',
    'mov': 'qrc:/qtx/icons/file-types/video.svg',
    'mp3': 'qrc:/qtx/icons/file-types/audio.svg',
    'mp4': 'qrc:/qtx/icons/file-types/video.svg',
    'mpeg': 'qrc:/qtx/icons/file-types/video.svg',
    'mpg': 'qrc:/qtx/icons/file-types/video.svg',
    'msi': 'qrc:/qtx/icons/file-types/install.svg',
    'mui': 'qrc:/qtx/icons/file-types/code.svg',
    'pdf': 'qrc:/qtx/icons/file-types/bill2.svg',
    'png': 'qrc:/qtx/icons/file-types/image.svg',
    'pot': 'qrc:/qtx/icons/file-types/bill2.svg',
    'potm': 'qrc:/qtx/icons/file-types/bill2.svg',
    'potx': 'qrc:/qtx/icons/file-types/bill2.svg',
    'ppam': 'qrc:/qtx/icons/file-types/bill2.svg',
    'pps': 'qrc:/qtx/icons/file-types/bill2.svg',
    'ppsm': 'qrc:/qtx/icons/file-types/bill2.svg',
    'ppsx': 'qrc:/qtx/icons/file-types/bill2.svg',
    'ppt': 'qrc:/qtx/icons/file-types/bill2.svg',
    'pptm': 'qrc:/qtx/icons/file-types/bill2.svg',
    'pptx': 'qrc:/qtx/icons/file-types/bill2.svg',
    'psd': 'qrc:/qtx/icons/file-types/image.svg',
    'pst': 'qrc:/qtx/icons/file-types/object.svg',
    'pub': 'qrc:/qtx/icons/file-types/code.svg',
    'rar': 'qrc:/qtx/icons/file-types/archive.svg',
    'rtf': 'qrc:/qtx/icons/file-types/text.svg',
    'sldm': 'qrc:/qtx/icons/file-types/bill2.svg',
    'sldx': 'qrc:/qtx/icons/file-types/bill2.svg',
    'swf': 'qrc:/qtx/icons/file-types/code.svg',
    'sys': 'qrc:/qtx/icons/file-types/settings.svg',
    'tif': 'qrc:/qtx/icons/file-types/image.svg',
    'tiff': 'qrc:/qtx/icons/file-types/image.svg',
    'tmp': 'qrc:/qtx/icons/file-types/settings.svg',
    'txt': 'qrc:/qtx/icons/file-types/text.svg',
    'vob': 'qrc:/qtx/icons/file-types/video.svg',
    'vsd': 'qrc:/qtx/icons/file-types/md.svg',
    'vsdm': 'qrc:/qtx/icons/file-types/md.svg',
    'vsdx': 'qrc:/qtx/icons/file-types/md.svg',
    'vss': 'qrc:/qtx/icons/file-types/md.svg',
    'vssm': 'qrc:/qtx/icons/file-types/md.svg',
    'vst': 'qrc:/qtx/icons/file-types/md.svg',
    'vstm': 'qrc:/qtx/icons/file-types/md.svg',
    'vstx': 'qrc:/qtx/icons/file-types/md.svg',
    'wav': 'qrc:/qtx/icons/file-types/audio.svg',
    'wbk': 'qrc:/qtx/icons/file-types/text.svg',
    'wma': 'qrc:/qtx/icons/file-types/audio.svg',
    'wmd': 'qrc:/qtx/icons/file-types/object.svg',
    'wmv': 'qrc:/qtx/icons/file-types/video.svg',
    'wpd': 'qrc:/qtx/icons/file-types/text.svg',
    'wp5': 'qrc:/qtx/icons/file-types/text.svg',
    'xla': 'qrc:/qtx/icons/file-types/settings.svg',
    'xlam': 'qrc:/qtx/icons/file-types/bill.svg',
    'xll': 'qrc:/qtx/icons/file-types/settings.svg',
    'xlm': 'qrc:/qtx/icons/file-types/bill.svg',
    'xls': 'qrc:/qtx/icons/file-types/bill.svg',
    'xlsm': 'qrc:/qtx/icons/file-types/bill.svg',
    'xlsx': 'qrc:/qtx/icons/file-types/bill.svg',
    'xlt': 'qrc:/qtx/icons/file-types/bill.svg',
    'xltm': 'qrc:/qtx/icons/file-types/bill.svg',
    'xltx': 'qrc:/qtx/icons/file-types/bill.svg',
    'xps': 'qrc:/qtx/icons/file-types/code.svg',
    'zip': 'qrc:/qtx/icons/file-types/archive.svg'
}